# Generated by Django 3.1 on 2022-04-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220420_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ls_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ls_admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ls_staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ls_superadmin',
            new_name='is_superadmin',
        ),
    ]
